// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microondas_backend.Data;

#nullable disable

namespace microondas_backend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("microondas_backend.Models.ProgramaAquecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alimento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaractereAquecimento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("Customizado")
                        .HasColumnType("bit");

                    b.Property<string>("Instrucoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Potencia")
                        .HasColumnType("int");

                    b.Property<int>("Tempo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaractereAquecimento")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("ProgramasAquecimento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alimento = "Pipoca (de micro-ondas)",
                            CaractereAquecimento = "*",
                            Customizado = false,
                            Instrucoes = "Observar o barulho de estouros do milho, caso houver um intervalo de mais de 10 segundos entre um estouro e outro, interrompa o aquecimento.",
                            Nome = "Pipoca",
                            Potencia = 7,
                            Tempo = 180
                        },
                        new
                        {
                            Id = 2,
                            Alimento = "Leite",
                            CaractereAquecimento = "~",
                            Customizado = false,
                            Instrucoes = "Cuidado com aquecimento de líquidos, o choque térmico aliado ao movimento do recipiente pode causar fervura imediata causando risco de queimaduras.",
                            Nome = "Leite",
                            Potencia = 5,
                            Tempo = 300
                        },
                        new
                        {
                            Id = 3,
                            Alimento = "Carne em pedaço ou fatias",
                            CaractereAquecimento = "#",
                            Customizado = false,
                            Instrucoes = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            Nome = "Carnes de boi",
                            Potencia = 4,
                            Tempo = 840
                        },
                        new
                        {
                            Id = 4,
                            Alimento = "Frango (qualquer corte)",
                            CaractereAquecimento = "+",
                            Customizado = false,
                            Instrucoes = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            Nome = "Frango",
                            Potencia = 7,
                            Tempo = 480
                        },
                        new
                        {
                            Id = 5,
                            Alimento = "Feijão congelado",
                            CaractereAquecimento = "@",
                            Customizado = false,
                            Instrucoes = "Deixe o recipiente destampado e em casos de plástico, cuidado ao retirar o recipiente pois o mesmo pode perder resistência em altas temperaturas.",
                            Nome = "Feijão",
                            Potencia = 9,
                            Tempo = 480
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
